-- MySQL Script generated by MySQL Workbench
-- Fri Nov  2 13:00:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cejosica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_cejosica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cejosica` DEFAULT CHARACTER SET utf8 ;
USE `bd_cejosica` ;

-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_estudiante` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `est_nie` VARCHAR(15) NOT NULL,
  `est_nombre` VARCHAR(100) NOT NULL,
  `est_apellido` VARCHAR(100) NOT NULL,
  `est_sexo` VARCHAR(20) NOT NULL,
  `est_foto` TEXT NULL,
  `est_estado_civil` VARCHAR(45) NULL DEFAULT 'Soltero',
  `est_fecha_nace` DATE NOT NULL,
  `est_edad` INT NOT NULL,
  `est_direccion` TEXT NOT NULL,
  `est_partida` VARCHAR(45) NULL,
  `est_dui` VARCHAR(45) NULL,
  `est_transporte` VARCHAR(45) NULL,
  `est_repite_grado` VARCHAR(45) NULL,
  `est_anio_ult` INT NULL,
  `est_depart` VARCHAR(45) NULL,
  `est_municipio` VARCHAR(45) NULL,
  `est_convivencia` VARCHAR(45) NULL,
  `est_discapacidad` VARCHAR(200) NULL,
  `est_dp_economica` VARCHAR(45) NULL,
  `est_fecha_registro` DATE NULL,
  `est_estado` VARCHAR(45) NULL DEFAULT 'Activo',
  PRIMARY KEY (`idestudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_parentesco` (
  `idtb_parentesco` INT NOT NULL AUTO_INCREMENT,
  `parent_nombre` VARCHAR(150) NOT NULL,
  `parent_dui` VARCHAR(10) NULL,
  `parent_telefono` VARCHAR(9) NULL,
  `parent_trabajo` VARCHAR(75) NULL,
  `parent_direccion` TEXT NULL,
  PRIMARY KEY (`idtb_parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_tipo_usuario` (
  `idtb_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idtb_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_usuario` (
  `idtb_usuario` INT NOT NULL AUTO_INCREMENT,
  `user_nombre` VARCHAR(100) NOT NULL,
  `user_apellido` VARCHAR(100) NOT NULL,
  `user_dui` VARCHAR(10) NULL,
  `user_nit` VARCHAR(20) NULL,
  `user_telefono` VARCHAR(45) NULL,
  `user_email` VARCHAR(75) NULL,
  `user_usuario` VARCHAR(100) NOT NULL,
  `user_clave` VARCHAR(100) NOT NULL,
  `user_profesion` VARCHAR(75) NULL,
  `user_estado` VARCHAR(45) NOT NULL DEFAULT 'Activo',
  `user_fecha_registro` DATE NULL,
  `user_cod_recup` VARCHAR(45) NULL,
  `user_idtb_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`idtb_usuario`, `user_idtb_tipo_usuario`),
  INDEX `fk_tb_usuario_tb_tipo_usuario1_idx` (`user_idtb_tipo_usuario` ASC),
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario1`
    FOREIGN KEY (`user_idtb_tipo_usuario`)
    REFERENCES `bd_cejosica`.`tb_tipo_usuario` (`idtb_tipo_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_materia` (
  `idtb_materia` INT NOT NULL AUTO_INCREMENT,
  `mate_nombre` VARCHAR(100) NOT NULL,
  `mate_descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtb_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_anio_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_anio_escolar` (
  `idtb_anio_escolar` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NOT NULL,
  `anio_fecha_inicio` DATE NOT NULL,
  `anio_fecha_final` DATE NOT NULL,
  `anio_descrip` TEXT NOT NULL,
  `anio_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_anio_escolar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_seccion` (
  `idtb_seccion` INT NOT NULL AUTO_INCREMENT,
  `sec_servicio_ed` VARCHAR(45) NOT NULL,
  `sec_turno` VARCHAR(45) NOT NULL,
  `sec_identificador` VARCHAR(45) NOT NULL,
  `sec_nivel` VARCHAR(45) NULL,
  `sec_vacante` INT NOT NULL,
  `sec_idtb_anio_escolar` INT NOT NULL,
  `sec_idtbuser` INT NOT NULL,
  PRIMARY KEY (`idtb_seccion`, `sec_idtb_anio_escolar`, `sec_idtbuser`),
  INDEX `fk_tb_seccion_tb_anio_escolar1_idx` (`sec_idtb_anio_escolar` ASC),
  INDEX `fk_tb_seccion_tb_usuario1_idx` (`sec_idtbuser` ASC),
  CONSTRAINT `fk_tb_seccion_tb_anio_escolar1`
    FOREIGN KEY (`sec_idtb_anio_escolar`)
    REFERENCES `bd_cejosica`.`tb_anio_escolar` (`idtb_anio_escolar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_seccion_tb_usuario1`
    FOREIGN KEY (`sec_idtbuser`)
    REFERENCES `bd_cejosica`.`tb_usuario` (`idtb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_materia_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_materia_user` (
  `mate_user_id` INT NOT NULL AUTO_INCREMENT,
  `mate_user_idtb_materia` INT NOT NULL,
  `mate_user_idtb_usuario` INT NOT NULL,
  PRIMARY KEY (`mate_user_id`, `mate_user_idtb_materia`, `mate_user_idtb_usuario`),
  INDEX `fk_tb_materia_has_tb_usuario_tb_usuario1_idx` (`mate_user_idtb_usuario` ASC),
  INDEX `fk_tb_materia_has_tb_usuario_tb_materia1_idx` (`mate_user_idtb_materia` ASC),
  CONSTRAINT `fk_tb_materia_has_tb_usuario_tb_materia1`
    FOREIGN KEY (`mate_user_idtb_materia`)
    REFERENCES `bd_cejosica`.`tb_materia` (`idtb_materia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_materia_has_tb_usuario_tb_usuario1`
    FOREIGN KEY (`mate_user_idtb_usuario`)
    REFERENCES `bd_cejosica`.`tb_usuario` (`idtb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_matricula` (
  `idtb_matricula` INT NOT NULL AUTO_INCREMENT,
  `matri_fecha` DATE NOT NULL,
  `matri_idestudiante` INT NOT NULL,
  `matri_idtb_seccion` INT NOT NULL,
  `matri_idtb_usuario` INT NOT NULL,
  PRIMARY KEY (`idtb_matricula`, `matri_idestudiante`, `matri_idtb_seccion`, `matri_idtb_usuario`),
  INDEX `fk_tb_matricula_tb_estudiante1_idx` (`matri_idestudiante` ASC),
  INDEX `fk_tb_matricula_tb_seccion1_idx` (`matri_idtb_seccion` ASC),
  INDEX `fk_tb_matricula_tb_usuario1_idx` (`matri_idtb_usuario` ASC),
  CONSTRAINT `fk_tb_matricula_tb_estudiante1`
    FOREIGN KEY (`matri_idestudiante`)
    REFERENCES `bd_cejosica`.`tb_estudiante` (`idestudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_matricula_tb_seccion1`
    FOREIGN KEY (`matri_idtb_seccion`)
    REFERENCES `bd_cejosica`.`tb_seccion` (`idtb_seccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_matricula_tb_usuario1`
    FOREIGN KEY (`matri_idtb_usuario`)
    REFERENCES `bd_cejosica`.`tb_usuario` (`idtb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_nota` (
  `idtb_nota` INT NOT NULL AUTO_INCREMENT,
  `not_p1_act1` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p1_act2` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p1_act3` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p1_promuno` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p2_act1` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p2_act2` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p2_act3` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p2_prom2` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p3-act1` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p3_act2` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p3_act3` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_p3_prom3` DECIMAL(10,2) NULL DEFAULT 0.0,
  `nota_prom_final` DECIMAL(10,2) NULL DEFAULT 0.0,
  `not_idtb_materia` INT NOT NULL,
  `not_idtb_matricula` INT NOT NULL,
  PRIMARY KEY (`idtb_nota`, `not_idtb_materia`, `not_idtb_matricula`),
  INDEX `fk_tb_nota_tb_materia1_idx` (`not_idtb_materia` ASC),
  INDEX `fk_tb_nota_tb_matricula1_idx` (`not_idtb_matricula` ASC),
  CONSTRAINT `fk_tb_nota_tb_materia1`
    FOREIGN KEY (`not_idtb_materia`)
    REFERENCES `bd_cejosica`.`tb_materia` (`idtb_materia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_nota_tb_matricula1`
    FOREIGN KEY (`not_idtb_matricula`)
    REFERENCES `bd_cejosica`.`tb_matricula` (`idtb_matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_seccion_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_seccion_materia` (
  `sec_mate_id` INT NOT NULL AUTO_INCREMENT,
  `sec_mate_idtb_seccion` INT NOT NULL,
  `sec_mate_idtb_materia` INT NOT NULL,
  PRIMARY KEY (`sec_mate_id`, `sec_mate_idtb_seccion`, `sec_mate_idtb_materia`),
  INDEX `fk_tb_seccion_has_tb_materia_tb_materia1_idx` (`sec_mate_idtb_materia` ASC),
  INDEX `fk_tb_seccion_has_tb_materia_tb_seccion1_idx` (`sec_mate_idtb_seccion` ASC),
  CONSTRAINT `fk_tb_seccion_has_tb_materia_tb_seccion1`
    FOREIGN KEY (`sec_mate_idtb_seccion`)
    REFERENCES `bd_cejosica`.`tb_seccion` (`idtb_seccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_seccion_has_tb_materia_tb_materia1`
    FOREIGN KEY (`sec_mate_idtb_materia`)
    REFERENCES `bd_cejosica`.`tb_materia` (`idtb_materia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cejosica`.`tb_parentesco_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cejosica`.`tb_parentesco_estudiante` (
  `tbid_parent_est` INT NOT NULL AUTO_INCREMENT,
  `tb_parentesco_id` INT NOT NULL,
  `tb_estudiante_id` INT NOT NULL,
  `tb_tipo` VARCHAR(45) NOT NULL,
  `tb_responsable` INT NOT NULL,
  PRIMARY KEY (`tbid_parent_est`, `tb_parentesco_id`, `tb_estudiante_id`),
  INDEX `fk_tb_parentesco_has_tb_estudiante_tb_estudiante1_idx` (`tb_estudiante_id` ASC),
  INDEX `fk_tb_parentesco_has_tb_estudiante_tb_parentesco1_idx` (`tb_parentesco_id` ASC),
  CONSTRAINT `fk_tb_parentesco_has_tb_estudiante_tb_parentesco1`
    FOREIGN KEY (`tb_parentesco_id`)
    REFERENCES `bd_cejosica`.`tb_parentesco` (`idtb_parentesco`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_parentesco_has_tb_estudiante_tb_estudiante1`
    FOREIGN KEY (`tb_estudiante_id`)
    REFERENCES `bd_cejosica`.`tb_estudiante` (`idestudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
